create table public.authors (
  id bigint generated by default as identity primary key,
  name text not null,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.genres (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  content text not null,
  date date not null,
  image text not null,
  is_featured boolean default false,
  author_id bigint references public.authors(id) not null,
  genre_id bigint references public.genres(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes
create index articles_date_idx on public.articles(date);
create index articles_title_idx on public.articles using gin(to_tsvector('english', title));
create index articles_author_id_idx on public.articles(author_id);
create index articles_genre_id_idx on public.articles(genre_id);

-- Add sample data
insert into public.authors (name, bio) values
  ('James Wilson', 'Electronic music journalist with 10 years of experience'),
  ('Sarah Johnson', 'Detroit-based music critic and event curator'),
  ('Maria Rodriguez', 'Techno historian and documentary filmmaker'),
  ('Alex Chen', 'Berlin correspondent and club culture specialist');

insert into public.genres (name, description) values
  ('IDM', 'Intelligent Dance Music - Complex electronic music with experimental elements'),
  ('Detroit Techno', 'The original techno sound born in Detroit'),
  ('Industrial Techno', 'Hard-hitting techno with industrial influences'),
  ('Minimal Techno', 'Stripped-down, hypnotic techno');

-- Insert articles with proper relationships
insert into public.articles (title, excerpt, content, date, image, author_id, genre_id, is_featured)
select
  'The Evolution of Detroit Techno: Past, Present, and Future',
  'Exploring how Detroit''s rich musical heritage continues to influence the global electronic music scene.',
  'Full article content here...',
  '2024-04-16',
  'https://images.unsplash.com/photo-1642178225043-f299072af862',
  (select id from public.authors where name = 'Maria Rodriguez'),
  (select id from public.genres where name = 'Detroit Techno'),
  true;