-- Create subscribers table
create table public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create comments table
create table public.comments (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) not null,
  user_name text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for comments
create index comments_article_id_idx on public.comments(article_id);
create index comments_created_at_idx on public.comments(created_at);