-- Create artists table
create table public.artists (
  id bigint generated by default as identity primary key,
  name text not null,
  bio text,
  genre text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create events table
create table public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  date date not null,
  location text not null,
  category text not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add sample artists
insert into public.artists (name, bio, genre, image) values
  ('Jeff Mills', 'Legendary Detroit techno pioneer and founder of Underground Resistance', 'Techno', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4'),
  ('Nina Kraviz', 'Influential DJ and producer known for her raw and energetic techno sets', 'Techno/Acid', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819'),
  ('Amelie Lens', 'Belgian techno producer and DJ known for her powerful, driving sound', 'Techno', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819');

-- Add sample events
insert into public.events (name, description, date, location, category, image) values
  ('Time Warp 2024', 'Legendary techno festival celebrating its 30th anniversary', '2024-06-15', 'Mannheim, Germany', 'Festival', 'https://images.unsplash.com/photo-1574169208507-84376144848b'),
  ('Berghain Weekender', 'Special 48-hour event featuring resident DJs', '2024-05-20', 'Berlin, Germany', 'Club Night', 'https://images.unsplash.com/photo-1571266028243-3716f02d2d2e'),
  ('Detroit Movement', 'Annual electronic music festival in the birthplace of techno', '2024-05-25', 'Detroit, USA', 'Festival', 'https://images.unsplash.com/photo-1642178225043-f299072af862');